import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// the settings object firebase needs to connect to our project
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
// tools to detect which platform the app is running on 

class DefaultFirebaseOptions {
// holds the firebase connection settings for each platform
// auto generated by the flutterfire tool
  static FirebaseOptions get currentPlatform {
  // picks the right settings based on where the app is running
    if (kIsWeb) {
      return web;
      // running in a browser, use the web settings
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
        // running on android, use the android settings
      default:
        throw UnsupportedError(
          'This app is configured for Android only.',
          // other platforms (ios, windows, etc) are not set up
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
  // keys that link the android app to our firebase project
    apiKey: 'AIzaSyBSDUTrwVNxvzElDv4BqKmJtK7Lopw9m9g',
    appId: '1:755261339439:android:f5f2aa361e748f6a8a93da',
    messagingSenderId: '755261339439',
    projectId: 'mbap-6e9d4',
    storageBucket: 'mbap-6e9d4.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
  // keys that link the web app to our firebase project
    apiKey: 'AIzaSyAKi4Df1dhd3CfR9SZFl24NNIKUIKA-ekw',
    appId: '1:755261339439:web:499fc56e15b7cc598a93da',
    messagingSenderId: '755261339439',
    projectId: 'mbap-6e9d4',
    authDomain: 'mbap-6e9d4.firebaseapp.com',
    storageBucket: 'mbap-6e9d4.firebasestorage.app',
    measurementId: 'G-FL3KR9CHZY',
  );
}
